### PR TITLE
chore(unity-docs): Update TapsellPlus Unity sdk version to 2.1.7

### PR DESCRIPTION
**Pull request by MortezaNedaei**

### CODE REVIEW

**Comment by mahdi-malv** [comment]
You forgot to update `adnetwork` versions (Admob -> 20.6.0)

**Review by mahdi-malv — CHANGES_REQUESTED** [review]
You forgot to update `adnetwork` versions (Admob -> 20.6.0)

**Comment by MortezaNedaei** [comment]
> You forgot to update `adnetwork` versions (Admob -> 20.6.0)

The Unity document is not yet complete. I changed its status to draft

**Review by MortezaNedaei — COMMENTED** [review]
ready to review

**Review by mahdi-malv — APPROVED** [review]

**Pull request merged**
